version: '3'
networks:
  mynet:
    driver: bridge
services:
  service-registry:
    hostname: register
    build:
      context: .
      dockerfile: "SRDockerfile"
    ports:
      - "8000:8000"
    environment:
      IP: "192.168.65.0"
      PORT: "8000"
      RING_SIZE: "32"
    networks:
      - mynet
  node-0-app:
    hostname: node0
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8101:8101"
    environment:
      NODE_IP: "192.168.65.6"
      NODE_PORT: "8101"
    networks:
      - mynet
    depends_on:
      - service-registry
  node-1-app:
    hostname: node1
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8102:8102"
    environment:
      NODE_IP: "192.168.65.7"
      NODE_PORT: "8102"
    networks:
      - mynet
    depends_on:
      - service-registry
  node-2-app:
    hostname: node2
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8103:8103"
    environment:
      NODE_IP: "192.168.65.5"
      NODE_PORT: "8103"
    networks:
      - mynet
    depends_on:
      - service-registry
  node-3-app:
    hostname: node3
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8104:8104"
    environment:
      NODE_IP: "192.168.65.4"
      NODE_PORT: "8104"
    networks:
      - mynet
    depends_on:
      - service-registry
  node-4-app:
    hostname: node4
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8105:8105"
    environment:
      NODE_IP: "192.168.65.3"
      NODE_PORT: "8105"
    networks:
      - mynet
    depends_on:
      - service-registry
  node-5-app:
    hostname: node5
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8106:8106"
    environment:
      NODE_IP: "192.168.65.8"
      NODE_PORT: "8106"
    networks:
      - mynet
    depends_on:
      - service-registry
  node-6-app:
    hostname: node6
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8107:8107"
    environment:
      NODE_IP: "192.168.65.9"
      NODE_PORT: "8107"
    networks:
      - mynet
    depends_on:
      - service-registry
  node-7-app:
    hostname: node7
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8108:8108"
    environment:
      NODE_IP: "192.168.65.10"
      NODE_PORT: "8108"
    networks:
      - mynet
    depends_on:
      - service-registry
  node-8-app:
    hostname: node8
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8109:8109"
    environment:
      NODE_IP: "192.168.65.11"
      NODE_PORT: "8109"
    networks:
      - mynet
    depends_on:
      - service-registry
  node-9-app:
    hostname: node9
    build:
      context: .
      dockerfile: "NodeDockerfile"
    ports:
      - "8110:8110"
    environment:
      NODE_IP: "192.168.65.12"
      NODE_PORT: "8110"
    networks:
      - mynet
    depends_on:
      - service-registry